model:
  type: LogisticRegression
  C: 0.3
  max_iter: 111

split:
  test_size: 0.2
  random_state: 42

paths:
  raw_data: data/raw/telco_churn.csv
  train_data: data/processed/train.csv
  test_data: data/processed/test.csv
  model_path: models/telco_churn.pkl
  metrics_path: metrics.json
